### ISSUE TITLE
condivisione con UACF7 PDF Generator

### ISSUE THREAD

**Issue by nzo1986** [MocioF/campi-moduli-italiani#11]
Nel ringraziarti per l'enorme ed interessante lavoro, ho riscontrato un piccolo bug, mentre per l'invio dell'email riesco a visualizzare il comune e la provincia, nella creazione del pdf trovo solo il codice, sbaglio qualcosa?
inoltro codice modulo:

   [comune* comune-nascita id:com wrapper_class:com class:com  kind:attuali placeholder "inserisci il comune di nascita"]
   <br>
   [submit id:Invia class:Invia "Invia"]

nel plugin UACF7 PDF Generator esclusivamente :

   [comune-nascita]

![Screenshot 2023-08-04 003005](https://github.com/MocioF/campi-moduli-italiani/assets/79604805/11830e99-a464-4a66-8241-a7b4eaba22b1)
![Screenshot 2023-08-04 003253](https://github.com/MocioF/campi-moduli-italiani/assets/79604805/7b18d10f-726e-4ce1-a421-61608bbdb4fa)

ringrazio per l'aiuto.

**Comment by MocioF** [comment]
Non conosco il funzionamento di UACF7 PDF Generator, ma credo che la cosa dipenda da quale valore decidi di utilizzare per il PDF.
Se il plugin ti fa scegliere quale campo utilizzare, campi-moduli-italiani mette a disposizione dei campi hidden per questo tipo di esigenze:
https://github.com/MocioF/campi-moduli-italiani/blob/5ba4d78966b45bf1e48fc5b7591611d25d4e5379/modules/comune/class-gcmi-comune-wpcf7-formtag.php#L196

**Comment by nzo1986** [comment]
grazie, cosi ho risolto perfettamente
