### ISSUE TITLE
Integrazione con Conditional Fields for Contact Form 7

### ISSUE THREAD

**Issue by vitomaria** [MocioF/campi-moduli-italiani#2]
Salve, le scrivo per sapere se esiste la possibilità di poter gestire la nazionalità ed il comune di provenienza tramite il plugin Conditional Fields for Contact Form 7. Mi spiego meglio: vorrei che una volta selezionata la nazionalità Italiana comparissero anche i campi per selezionare il comune di provenienza. Alcuni utenti del mio sito sono nati all'estero quindi selezionare il comune di provenienza non ha senso per loro (anche perché esistono solo i comuni italiani nel vostro plugin). Vorrei che il campo per il comune scomparisse una volta selezionato lo stato estero. Conditional Fields for Contact Form 7 permette di fare ciò con i campi select ma con il vostro plugin non è possibile... ci sono dei campi select "particolari"...

**Comment by MocioF** [comment]
Buona sera,
Conditional Fields è il sistema che uso io per la medesima esigenza.
Può vedere un esempio su questa pagina:
https://www.vivatacademia.org/chi-siamo/iscriviti-a-vivat-academia/

**Comment by vitomaria** [comment]
Grazie per la risposta. Purtroppo ancora non ho capito come fare. Potrebbe postarmi lo pseudocodice che ha utilizzato?
Io ho utilizzato questo:
<label> Nazionalità [stato* stato class:stato use_continent only_current "ITA"] </label>
[group comuni-italia]<label> Nata/o a:[comune comuni wrapper_class:comuni kind:attuali]</label>[/group]
La condizionalità è questa:
![image](https://user-images.githubusercontent.com/29692803/154767176-6c4f0f00-dfbb-4284-9f18-87937ffce4b3.png)

**Comment by MocioF** [comment]
Questo è lo pseudo codice utilizzato per il comune di nascita (senza le labels):

[stato* paese-nascita id:paese-nascita first_as_label use_continent "100"]

[group group-comune-estero-nas clear_on_hide inline][text* comu-nascita-estero id:comu-nascita-estero placeholder "Città estera nascita"][/group]
[group group-comune-italia-nas clear_on_hide inline][comune* comu-nascita-italia id:comu-nascita-italia use_label_element wrapper_class:esterno-oriz class:interno-oriz kind:evidenza_cessati][/group]

Stessa cosa faccio per la residenza, ma qui utilizzo solo i comuni attuali.

Le condizionalità sono quelle nell'immagine.
![Screenshot_20220219-013048_Chrome](https://user-images.githubusercontent.com/26635356/154778181-738e38a3-d5ec-48e6-bafd-6160b9be4bf9.jpg)

**Comment by MocioF** [comment]
Il campo Comune ha come valore il codice ISTAT del comune e quello stato il codice ISTAT dello stato. Per l'Italia, il codice è 100.

**Comment by vitomaria** [comment]
Grazie mille. Era questione di codice statistico. Avevo fatto una veloce ricerca su Google e credevo fosse "ITA" il codice giusto. Per questo motivo non funzionava nulla. Grazie per questo plugin, stai dando una mano a tante persone compreso me! Un abbraccio!
