### ISSUE TITLE
Errore 500

### ISSUE THREAD

**Issue by vitomaria** [MocioF/campi-moduli-italiani#4]
Salve,
utilizzo WordPress 6.0, CF7 5.6 e Campi Moduli Italiani 2.0.6.
Negli ultimi tempi ho riscontrato in un modulo per associarsi questo tipo di errore:
Response {type: 'basic', url: 'https://xxxxxxxxx.it/wp-json/contact-form-7/v1/contact-forms/2134/feedback', redirected: false, status: 500, ok: false, …}body: (…)bodyUsed: falseheaders: Headers {}ok: falseredirected: falsestatus: 500statusText: ""type: "basic"url: "https://xxxxxxxxxxxxx.it/wp-json/contact-form-7/v1/contact-forms/2134/feedback"[[Prototype]]: ResponsearrayBuffer: ƒ arrayBuffer()blob: ƒ blob()body: (…)bodyUsed: (…)clone: ƒ clone()formData: ƒ formData()headers: (…)json: ƒ json()ok: (…)redirected: (…)status: (…)statusText: (…)text: ƒ text()type: (…)url: (…)constructor: ƒ Response()Symbol(Symbol.toStringTag): "Response"get body: ƒ body()get bodyUsed: ƒ bodyUsed()get headers: ƒ headers()get ok: ƒ ok()get redirected: ƒ redirected()get status: ƒ status()get statusText: ƒ statusText()get type: ƒ type()get url: ƒ url()[[Prototype]]: Object
(anonimo) @ index.js?ver=5.6:1
Promise.catch (asinc)
$ @ index.js?ver=5.6:1
(anonimo) @ index.js?ver=5.6:1
Promise.then (asinc)
then @ recaptcha__it.js:156
o @ index.js?ver=5.6:1
wpcf7.submit @ index.js?ver=5.6:1
(anonimo) @ index.js?ver=5.6:1

Ho disabilitato tutti i plugin e cambiato tema. Il problema viene solo da questo magnifico plugin...

**Comment by MocioF** [comment]
Il problema dipende dalla versione di CF7. CF7 dalla versione 5.6 ha modificato il sistema di validazione dei campi che veniva sfruttato anche da questo plugin.
Nei prossimi giorni verrà rilasciata una versione compatibile con CF7 5.6 che, tuttavia, non utilizzerà le nuove funzionalità di validazione implementate nel gestore dei form (questa implementazione verrà effettuata successivamente)
