### ISSUE TITLE
Versione 6.0 di Wordpress

### ISSUE THREAD

**Issue by jackrosso** [MocioF/campi-moduli-italiani#5]
Il plugin non funziona con la versione 6.0 E' possibile aggiornarlo per farlo funzionare?

**Comment by MocioF** [comment]
Buongiorno,
il plugin non è stato dichiarato compatibile con WP 6.0 perché ho rilevato diversi problemi.
Sto lavorando ad una versione aggiornata che sarà presumibilmente rilasciata entro la fine del mese di luglio.
Al momento, sto riscrivendo parte del codice per renderlo compatibile e mantenibile anche per futuri rilasci di WP.
